#!/bin/bash
#PBS -N megatron-test
#PBS -l select=4:ngpus=8
#PBS -l place=scatter
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -o megatron-test.log
#PBS -P gs_ccds_chen.wang
#PBS -q gpu_as


GPUS_PER_NODE=8
TP_SIZE=8
PP_SIZE=1

MASTER_ADDR=$(head -1 "${PBS_NODEFILE}")
MASTER_PORT=29500
NUM_NODES=$(wc -l < "${PBS_NODEFILE}")

export GPUS_PER_NODE NUM_NODES TP_SIZE PP_SIZE MASTER_ADDR MASTER_PORT

DP_SIZE=$(( NUM_NODES * GPUS_PER_NODE / (TP_SIZE * PP_SIZE) ))

PROJ_DIR=$HOME/Megatron-LM
cd $PROJ_DIR

module load cuda/13.0 gnu/gcc-12.3
eval "$(/usr/local/anaconda2025/bin/conda shell.bash hook)"
conda activate megatron-lm

echo "====== PBS_NODEFILE ======"
cat $PBS_NODEFILE

# Topology
mpirun --mca plm_rsh_agent pbs_tmrsh \
       -hostfile $PBS_NODEFILE -np $NUM_NODES -- bash -c '
  RANK=$PMI_RANK
  {
    echo "===== HOST: $(hostname) ====="
    nvidia-smi nvlink -s
    nvidia-smi topo -m
    nvidia-smi
    nvidia-smi --query-gpu=index,uuid --format=csv,noheader
    echo "CUDA_VISIBLE_DEVICES on $(hostname): $CUDA_VISIBLE_DEVICES"
  } | sed "s/^/[node${RANK}] /"
'

export CUDA_VISIBLE_DEVICES=$(seq 0 $((GPUS_PER_NODE - 1)) | paste -sd ',')

export NUM_LAYERS=4
export MICRO_BATCH_SIZE=8
export GLOBAL_BATCH_SIZE=128
export TRAIN_SAMPLES=1280

export MEGATRON_PROFILE=0 MERGE_MEGATRON_PROFILE=1 TRACE_DIR=megatron_trace_dp${DP_SIZE}_pp${PP_SIZE}_tp${TP_SIZE}

mpirun --mca plm_rsh_agent pbs_tmrsh \
       -hostfile $PBS_NODEFILE -np $NUM_NODES \
       -x GPUS_PER_NODE -x NUM_NODES \
       -x TP_SIZE -x PP_SIZE \
       -x MASTER_ADDR -x MASTER_PORT \
       -x CUDA_VISIBLE_DEVICES \
       -x NUM_LAYERS -x MICRO_BATCH_SIZE \
       -x GLOBAL_BATCH_SIZE -x TRAIN_SAMPLES \
       -x MEGATRON_PROFILE -x MERGE_MEGATRON_PROFILE \
       -x TRACE_DIR -x SCRATCH \
       bash -c '
         module purge
         module load cuda/13.0 gnu/gcc-12.3
         eval "$(/usr/local/anaconda2025/bin/conda shell.bash hook)"
         conda activate megatron-lm
         bash examples/llama/hpcc/train_llama_hpcc.sh
       ' 2>&1 | tee train_llama_hpcc.log