#!/bin/bash
#PBS -N megatron-install
#PBS -l select=1:ngpus=8
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -o megatron-install.log
#PBS -P gs_ccds_chen.wang
#PBS -q gpu_as

set -euo pipefail

module purge
module load cuda/13.0 gnu/gcc-12.3
eval "$(/usr/local/anaconda2025/bin/conda shell.bash hook)"

conda create -n megatron-lm python=3.12 -y
conda activate megatron-lm
conda install openmpi -c conda-forge -y
pip install torch==2.11.0 --index-url https://download.pytorch.org/whl/cu130 2>&1 | tee install.log

# sys runtime and nvml.h
export CUDA_HOME=${CUDA_HOME:-$(dirname $(dirname $(which nvcc)))}
export CPATH=$CUDA_HOME/include
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
# conda NCCL
CONDA_NVIDIA_PKG=$CONDA_PREFIX/lib/python3.12/site-packages/nvidia
export CPATH=$CONDA_NVIDIA_PKG/nccl/include:$CONDA_NVIDIA_PKG/cudnn/include:$CPATH
export LD_LIBRARY_PATH=$CONDA_NVIDIA_PKG/nccl/lib:$CONDA_NVIDIA_PKG/cudnn/lib:$LD_LIBRARY_PATH

export APEX_SED_EXTRA="sed -i '410,411d' apex/setup.py"

bash "$(dirname "$0")/../../install.sh"
