#!/bin/bash
#PBS -N megatron-install
#PBS -l select=1:ngpus=8
#PBS -l walltime=02:00:00
#PBS -j oe
#PBS -o megatron-install.log
#PBS -P 52001006

set -euo pipefail

cd $HOME/Megatron-LM

module purge
module load cuda/12.6.2 openmpi/5.0.5-gcc11-cuda12.6
eval "$(/home/app/apps/miniforge3/24.3.0/bin/conda shell.bash hook)"

conda create -n megatron-lm python=3.12 -y
conda activate megatron-lm
pip install torch==2.11.0 --index-url https://download.pytorch.org/whl/cu126 2>&1 | tee install.log

# sys runtime and nvml.h
export CUDA_HOME=${CUDA_HOME:-$(dirname $(dirname $(which nvcc)))}
export CPATH=$CUDA_HOME/include
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
# conda NCCL
CONDA_NVIDIA_PKG=$CONDA_PREFIX/lib/python3.12/site-packages/nvidia
export CPATH=$CONDA_NVIDIA_PKG/nccl/include:$CONDA_NVIDIA_PKG/cudnn/include:$CPATH
export LD_LIBRARY_PATH=$CONDA_NVIDIA_PKG/nccl/lib:$CONDA_NVIDIA_PKG/cudnn/lib:$LD_LIBRARY_PATH

echo "Install nvidia-resiliency-ext"
if [ ! -d "nvidia-resiliency-ext" ]; then
    echo "Cloning"
    git clone https://github.com/NVIDIA/nvidia-resiliency-ext.git -b v0.5.0
fi
cd nvidia-resiliency-ext
pip install poetry pybind11
pip install -v --no-build-isolation -e . 2>&1 | tee -a ../install.log
cd ..


echo "Install megatron-core"
pip install -v --no-build-isolation -e . 2>&1 | tee -a install.log


echo "Install dependencies"
pip install uv cmake

uv pip install -v --no-build-isolation --group build 2>&1 | tee -a install.log
uv pip install -v --no-build-isolation ".[training,dev]" 2>&1 | tee -a install.log


echo "Install apex"
# install apex
if [ ! -d "apex" ]; then
    echo "Cloning apex"
    git clone https://github.com/NVIDIA/apex.git -b 25.09
    # nvcc and torch version mismatch
    sed -i '84,92s/^/#/' apex/setup.py
    sed -i '410,411d' apex/setup.py
fi 

cd apex
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./ 2>&1 | tee -a ../install.log
cd ..