#!/bin/bash
#PBS -q ai
#PBS -N megatron-install
#PBS -l select=1:ngpus=1
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -o megatron-install.log
#PBS -P 52001005

set -euo pipefail

cd $HOME/Megatron-LM

module load miniforge3/25.3.1 gcc/12.2.0-nscc cuda/12.2.2 git/2.39.2

# sys CUDA Runtime
conda create -n megatron-lm python=3.12 -y
conda activate megatron-lm
pip install torch==2.8.0 2>&1 | tee install.log


echo "Install nvidia-resiliency-ext"
if [ ! -d "nvidia-resiliency-ext" ]; then
    echo "Cloning"
    git clone https://github.com/NVIDIA/nvidia-resiliency-ext.git -b v0.5.0
fi
cd nvidia-resiliency-ext
pip install poetry pybind11
pip install -v --no-build-isolation -e . 2>&1 | tee -a ../install.log
cd ..


echo "Install megatron-core"
pip install -v --no-build-isolation -e . 2>&1 | tee -a install.log


echo "Install dependencies"
pip install uv cmake

# sys runtime and nvml.h
export CPATH=/app/apps/cuda/12.2.2/include:$CPATH
export LIBRARY_PATH=/app/apps/cuda/12.2.2/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=/app/apps/cuda/12.2.2/lib64:$LD_LIBRARY_PATH
# conda NCCL
CONDA_NVIDIA_PKG=$CONDA_PREFIX/lib/python3.12/site-packages/nvidia
export CPATH=$CONDA_NVIDIA_PKG/nccl/include:$CONDA_NVIDIA_PKG/cudnn/include:$CPATH
export LIBRARY_PATH=$CONDA_NVIDIA_PKG/nccl/lib:$CONDA_NVIDIA_PKG/cudnn/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CONDA_NVIDIA_PKG/nccl/lib:$CONDA_NVIDIA_PKG/cudnn/lib:$LD_LIBRARY_PATH

uv pip install -v --no-build-isolation --group build 2>&1 | tee -a install.log
uv pip install -v --no-build-isolation ".[training,dev]" 2>&1 | tee -a install.log


echo "Install apex"
# install apex
if [ ! -d "apex" ]; then
    echo "Cloning apex"
    git clone https://github.com/NVIDIA/apex.git -b 25.09
    # nvcc and torch version mismatch
    sed -i '84,92s/^/#/' apex/setup.py
fi 

cd apex
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./ 2>&1 | tee -a ../install.log
cd ..
