#!/bin/bash
#PBS -q ai
#PBS -N megatron-test
#PBS -l select=1:ngpus=4
#PBS -l walltime=02:01:00
#PBS -j oe
#PBS -o megatron-test.log
#PBS -P 52001005

GPUS_PER_NODE=4
TP_SIZE=2
PP_SIZE=2

NUM_NODES=$(wc -l < "${PBS_NODEFILE}")

PROJ_DIR=$HOME/Megatron-LM
cd $PROJ_DIR

module load miniforge3/25.3.1 gcc/12.2.0-nscc cuda/12.2.2 git/2.39.2
conda activate megatron-lm

echo "====== PBS_NODEFILE ======"
cat $PBS_NODEFILE

# Topology
mpirun -np $NUM_NODES -- bash -c '
  RANK=$PMI_RANK
  {
    echo "===== HOST: $(hostname) ====="
    nvidia-smi nvlink -s
    nvidia-smi topo -m
    nvidia-smi
    nvidia-smi --query-gpu=index,uuid --format=csv,noheader
    echo "CUDA_VISIBLE_DEVICES on $(hostname): $CUDA_VISIBLE_DEVICES"
  } | sed "s/^/[node${RANK}] /"
'

# Necessary for aspire2a to set
export CUDA_VISIBLE_DEVICES=$(seq 0 $((GPUS_PER_NODE - 1)) | paste -sd ',')

MASTER_ADDR=$(head -1 "${PBS_NODEFILE}")
MASTER_PORT=29500

NUM_LAYERS=4

export GPUS_PER_NODE NUM_NODES TP_SIZE PP_SIZE NUM_LAYERS MASTER_ADDR MASTER_PORT

mpirun -np $NUM_NODES bash examples/llama/aspire2a/train_llama_aspire2a.sh
