#!/bin/bash
#PBS -q ai
#PBS -N megatron-test
#PBS -l select=8:ngpus=1
#PBS -l place=scatter
#PBS -l walltime=02:01:00
#PBS -j oe
#PBS -o megatron-test.log
#PBS -P 52001005

export GPUS_PER_NODE=1
export TP_SIZE=1
export PP_SIZE=4

export VIRTUAL_STAGE_PER_RANK=2
export NUM_LAYERS=8
export MICRO_BATCH_SIZE=4
export GLOBAL_BATCH_SIZE=64
export TRAIN_SAMPLES=$(( GLOBAL_BATCH_SIZE * 3 ))
export SEQ_LENGTH=4096
export BUCKET_SIZE=0
export ENABLE_RECOMPUTE=0
export ENABLE_FSDP=1  # Set to ZeRO-2
export MEGATRON_PROFILE=1 MERGE_MEGATRON_PROFILE=1 MEGATRON_PROFILE_STACK=1

export MASTER_ADDR=$(head -1 "${PBS_NODEFILE}")
export MASTER_PORT=29500
export NUM_NODES=$(wc -l < "${PBS_NODEFILE}")

DP_SIZE=$(( NUM_NODES * GPUS_PER_NODE / (TP_SIZE * PP_SIZE) ))

PROJ_DIR=$HOME/Megatron-LM
cd $PROJ_DIR

module load miniforge3/25.3.1 gcc/12.2.0-nscc cuda/12.2.2 git/2.39.2
conda activate megatron-lm

echo "====== PBS_NODEFILE ======"
cat $PBS_NODEFILE

# Topology
mpirun -np $NUM_NODES -- bash -c '
  RANK=$PMI_RANK
  {
    echo "===== HOST: $(hostname) ====="
    nvidia-smi nvlink -s
    nvidia-smi topo -m
    nvidia-smi
    nvidia-smi --query-gpu=index,uuid --format=csv,noheader
    echo "CUDA_VISIBLE_DEVICES on $(hostname): $CUDA_VISIBLE_DEVICES"
  } | sed "s/^/[node${RANK}] /"
'

# Necessary for aspire2a to set
export CUDA_VISIBLE_DEVICES=$(seq 0 $((GPUS_PER_NODE - 1)) | paste -sd ',')

if [[ $ENABLE_FSDP -gt 0 ]]; then
  export TRACE_DIR=$SCRATCH/megatron_trace_fsdp${DP_SIZE}_pp${PP_SIZE}_tp${TP_SIZE}_bucket${BUCKET_SIZE}
else
  export TRACE_DIR=$SCRATCH/megatron_trace_dp${DP_SIZE}_pp${PP_SIZE}_tp${TP_SIZE}_bucket${BUCKET_SIZE}
fi

mpirun -np $NUM_NODES bash examples/llama/aspire2a/train_llama_aspire2a.sh 2>&1 | tee train_llama_aspire2a.log


if [[ $MEGATRON_PROFILE -gt 0 ]]; then
  cp train_llama_aspire2a.log $TRACE_DIR
fi