#!/bin/bash
#PBS -q ai
#PBS -N megatron-test
#PBS -l select=4:ngpus=1
#PBS -l place=scatter
#PBS -l walltime=02:01:00
#PBS -j oe
#PBS -o megatron-test.log
#PBS -P 52001005

GPUS_PER_NODE=1
TP_SIZE=1
PP_SIZE=2

MASTER_ADDR=$(head -1 "${PBS_NODEFILE}")
MASTER_PORT=29500
NUM_NODES=$(wc -l < "${PBS_NODEFILE}")

export GPUS_PER_NODE NUM_NODES TP_SIZE PP_SIZE MASTER_ADDR MASTER_PORT

DP_SIZE=$(( NUM_NODES * GPUS_PER_NODE / (TP_SIZE * PP_SIZE) ))

PROJ_DIR=$HOME/Megatron-LM
cd $PROJ_DIR

module load miniforge3/25.3.1 gcc/12.2.0-nscc cuda/12.2.2 git/2.39.2
conda activate megatron-lm

echo "====== PBS_NODEFILE ======"
cat $PBS_NODEFILE

# Topology
mpirun -np $NUM_NODES -- bash -c '
  RANK=$PMI_RANK
  {
    echo "===== HOST: $(hostname) ====="
    nvidia-smi nvlink -s
    nvidia-smi topo -m
    nvidia-smi
    nvidia-smi --query-gpu=index,uuid --format=csv,noheader
    echo "CUDA_VISIBLE_DEVICES on $(hostname): $CUDA_VISIBLE_DEVICES"
  } | sed "s/^/[node${RANK}] /"
'

# Necessary for aspire2a to set
export CUDA_VISIBLE_DEVICES=$(seq 0 $((GPUS_PER_NODE - 1)) | paste -sd ',')

export NUM_LAYERS=4
export MICRO_BATCH_SIZE=8
export GLOBAL_BATCH_SIZE=128
export TRAIN_SAMPLES=512

export MEGATRON_PROFILE=1 MERGE_MEGATRON_PROFILE=1 TRACE_DIR=megatron_trace_dp${DP_SIZE}_pp${PP_SIZE}_tp${TP_SIZE}

mpirun -np $NUM_NODES bash examples/llama/aspire2a/train_llama_aspire2a.sh 2>&1 | tee train_llama_aspire2a.log
